# Generated by Django 3.1.5 on 2021-02-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, verbose_name='Пользователь')),
            ],
        ),
    ]
