# Generated by Django 3.1.5 on 2021-04-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20210403_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
