# Generated by Django 3.1.5 on 2021-01-18 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_auto_20200828_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accumulator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Номер')),
                ('date_change', models.DateField(auto_now_add=True, verbose_name='Дата установки')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Примечания')),
            ],
        ),
        migrations.CreateModel(
            name='DataCollectTerminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Наименование')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Серийный номер')),
                ('mac_address', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='MAC-адрес')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('accumulator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dct.accumulator', verbose_name='Аккумулятор')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.profile', verbose_name='Пользователь')),
            ],
        ),
    ]
