# Generated by Django 3.1.5 on 2021-02-27 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accumulator',
            fields=[
                ('number', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='Номер')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Аккумулятор',
                'verbose_name_plural': 'Аккумуляторы',
            },
        ),
        migrations.CreateModel(
            name='DataCollectTerminal',
            fields=[
                ('name', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('model', models.IntegerField(choices=[(1, 'Motorola MC7596'), (2, 'Motorola MC7598'), (3, 'Motorola MC7090'), (4, 'Motorola MC9090ER'), (5, 'Intermec CK3a1'), (6, 'Intermec CK3n1')], default=1, verbose_name='Модель')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Серийный номер')),
                ('mac_address', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='MAC-адрес')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('accumulator', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dct.accumulator', verbose_name='Аккумулятор')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.client', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'ТСД',
                'verbose_name_plural': 'ТСД',
            },
        ),
        migrations.CreateModel(
            name='DataCollectTerminalRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('data_collect_terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dct.datacollectterminal')),
            ],
        ),
        migrations.CreateModel(
            name='AccumulatorDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('state', models.IntegerField(choices=[(1, 'Install'), (2, 'Uninstall')], default=1, verbose_name='Состояние')),
                ('accumulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dct.accumulator', verbose_name='Дата изменения состояния')),
            ],
        ),
    ]
