# Generated by Django 3.1.5 on 2021-01-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accumulator',
            name='date_change',
            field=models.DateField(verbose_name='Дата установки'),
        ),
    ]
