# Generated by Django 3.1.5 on 2021-01-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0002_auto_20210118_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollectterminal',
            name='model',
            field=models.IntegerField(choices=[(1, 'Motorola MC7596'), (2, 'Motorola MC7598'), (3, 'Motorola MC7090'), (4, 'Motorola MC9090ER'), (5, 'Intermec CK3a1'), (6, 'Intermec CK3n1')], default=1, max_length=1, verbose_name='Модель'),
        ),
    ]
