# Generated by Django 3.1.5 on 2021-04-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0003_accumulator_date_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollectterminal',
            name='debited',
            field=models.BooleanField(default=False, verbose_name='Списан'),
        ),
        migrations.AddField(
            model_name='datacollectterminal',
            name='repair',
            field=models.BooleanField(default=False, verbose_name='В ремонте'),
        ),
    ]
