# Generated by Django 3.1.5 on 2021-04-03 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0004_auto_20210403_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accumulator',
            name='date_purchase',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата закупки'),
            preserve_default=False,
        ),
    ]
