# Generated by Django 3.1.5 on 2021-01-20 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0004_auto_20210118_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accumulator',
            options={'verbose_name': 'Аккумулятор', 'verbose_name_plural': 'Аккумуляторы'},
        ),
        migrations.AlterModelOptions(
            name='datacollectterminal',
            options={'verbose_name': 'ТСД', 'verbose_name_plural': 'ТСД'},
        ),
        migrations.AlterField(
            model_name='datacollectterminal',
            name='accumulator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dct.accumulator', verbose_name='Аккумулятор'),
        ),
    ]
