# Generated by Django 3.1.5 on 2021-01-20 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200828_1021'),
        ('dct', '0005_auto_20210120_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollectterminal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.profile', verbose_name='Пользователь'),
        ),
    ]
