# Generated by Django 3.1.5 on 2021-04-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0005_auto_20210403_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='accumulator',
            name='debited',
            field=models.BooleanField(default=False, verbose_name='Списан'),
        ),
    ]
