# Generated by Django 3.1.5 on 2021-02-11 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('dct', '0006_auto_20210120_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollectterminal',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='datacollectterminal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.client', verbose_name='Пользователь'),
        ),
    ]
