# Generated by Django 3.1.5 on 2021-02-12 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0007_auto_20210211_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accumulator',
            name='date_change',
        ),
        migrations.AlterField(
            model_name='accumulator',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.CreateModel(
            name='AccumulatorDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('remark', models.IntegerField(choices=[(1, 'Install'), (2, 'Uninstall')], default=1, verbose_name='Состояние')),
                ('accumulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dct.accumulator', verbose_name='Дата изменения состояния')),
            ],
        ),
    ]
