# Generated by Django 3.1.5 on 2021-02-12 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0008_auto_20210212_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accumulator',
            old_name='remark',
            new_name='state',
        ),
    ]
