# Generated by Django 3.1.5 on 2021-02-16 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0012_datacollectterminalremark'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollectterminal',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
