# Generated by Django 3.1.5 on 2021-02-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0013_datacollectterminal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollectterminalremark',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
