# Generated by Django 3.1.5 on 2021-02-25 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('dct', '0014_auto_20210216_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollectterminal',
            name='accumulator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dct.accumulator', unique=True, verbose_name='Аккумулятор'),
        ),
        migrations.AlterField(
            model_name='datacollectterminal',
            name='serial_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='datacollectterminal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.client', unique=True, verbose_name='Пользователь'),
        ),
    ]
