# Generated by Django 3.1.5 on 2021-02-25 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dct', '0016_auto_20210225_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollectterminal',
            name='accumulator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dct.accumulator', verbose_name='Аккумулятор'),
        ),
    ]
